version: 2

before:
  hooks:
    - go mod tidy
    - go fmt ./...

builds:
  - id: kijo-agent
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: kijo-agent

dockers:
  - image_templates:
      - "ghcr.io/kijosec/agent:{{ .Tag }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    goarch: amd64

  - image_templates:
      - "ghcr.io/kijosec/agent:{{ .Tag }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/kijosec/agent:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kijosec/agent:{{ .Tag }}-amd64"
      - "ghcr.io/kijosec/agent:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/kijosec/agent:latest"
    image_templates:
      - "ghcr.io/kijosec/agent:{{ .Tag }}-amd64"
      - "ghcr.io/kijosec/agent:{{ .Tag }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kijosec
    name: agent
  draft: false
  prerelease: auto
