version: 2

project_name: trix-agent

before:
  hooks:
    - go mod tidy

builds:
  - id: trix-agent
    main: ./cmd
    binary: trix-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: trix-agent
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - image_templates:
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{ .Version }}"
    dockerfile: Dockerfile
    goarch: amd64

  - image_templates:
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VERSION={{ .Version }}"
    dockerfile: Dockerfile
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/trixsec/trix-agent:{{ .Version }}"
    image_templates:
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-amd64"
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-arm64"

  - name_template: "ghcr.io/trixsec/trix-agent:latest"
    image_templates:
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-amd64"
      - "ghcr.io/trixsec/trix-agent:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
